INSERT INTO statuts (created_at, updated_at) VALUES (NOW(), NOW());
INSERT INTO statuts (created_at, updated_at) VALUES (NOW(), NOW());
INSERT INTO statuts (created_at, updated_at) VALUES (NOW(), NOW());

INSERT INTO isolations (created_at, updated_at) VALUES (NOW(), NOW());
INSERT INTO isolations (created_at, updated_at) VALUES (NOW(), NOW());
INSERT INTO isolations (created_at, updated_at) VALUES (NOW(), NOW());

INSERT INTO securites (created_at, updated_at) VALUES (NOW(), NOW());
INSERT INTO securites (created_at, updated_at) VALUES (NOW(), NOW());
INSERT INTO securites (created_at, updated_at) VALUES (NOW(), NOW());


INSERT INTO typepieces (created_at, updated_at) VALUES (NOW(), NOW());
INSERT INTO typepieces (created_at, updated_at) VALUES (NOW(), NOW());
INSERT INTO typepieces (created_at, updated_at) VALUES (NOW(), NOW());

INSERT INTO typeappartements (created_at, updated_at) VALUES (NOW(), NOW());
INSERT INTO typeappartements (created_at, updated_at) VALUES (NOW(), NOW());
INSERT INTO typeappartements (created_at, updated_at) VALUES (NOW(), NOW());

INSERT INTO typeappareils (created_at, updated_at) VALUES (NOW(), NOW());
INSERT INTO typeappareils (created_at, updated_at) VALUES (NOW(), NOW());
INSERT INTO typeappareils (created_at, updated_at) VALUES (NOW(), NOW());

INSERT INTO regions (nomregion, created_at, updated_at) VALUES ('Auvergne-Rhône-Alpes', NOW(), NOW());
INSERT INTO regions (nomregion, created_at, updated_at) VALUES ('Bourgogne-Franche-Comté', NOW(), NOW());
INSERT INTO regions (nomregion, created_at, updated_at) VALUES ('Bretagne', NOW(), NOW());
INSERT INTO regions (nomregion, created_at, updated_at) VALUES ('Centre-Val de Loire', NOW(), NOW());
INSERT INTO regions (nomregion, created_at, updated_at) VALUES ('Corse', NOW(), NOW());
INSERT INTO regions (nomregion, created_at, updated_at) VALUES ('Grand Est', NOW(), NOW());
INSERT INTO regions (nomregion, created_at, updated_at) VALUES ('Hauts-de-France', NOW(), NOW());
INSERT INTO regions (nomregion, created_at, updated_at) VALUES ('Île-de-France', NOW(), NOW());
INSERT INTO regions (nomregion, created_at, updated_at) VALUES ('Normandie', NOW(), NOW());
INSERT INTO regions (nomregion, created_at, updated_at) VALUES ('Nouvelle-Aquitaine', NOW(), NOW());
INSERT INTO regions (nomregion, created_at, updated_at) VALUES ('Occitanie', NOW(), NOW());
INSERT INTO regions (nomregion, created_at, updated_at) VALUES ('Pays de la Loire', NOW(), NOW());
INSERT INTO regions (nomregion, created_at, updated_at) VALUES ('Provence-Alpes-Côte d''Azur', NOW(), NOW());
INSERT INTO regions (nomregion, created_at, updated_at) VALUES ('Guadeloupe', NOW(), NOW());
INSERT INTO regions (nomregion, created_at, updated_at) VALUES ('Guyane', NOW(), NOW());
INSERT INTO regions (nomregion, created_at, updated_at) VALUES ('Martinique', NOW(), NOW());
INSERT INTO regions (nomregion, created_at, updated_at) VALUES ('La Réunion', NOW(), NOW());
INSERT INTO regions (nomregion, created_at, updated_at) VALUES ('Mayotte', NOW(), NOW());

INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Ain",	1, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Aisne",	7, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Allier",	1, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Alpes-de-Haute-Provence",	13, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Hautes-Alpes",	13, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Alpes-Maritimes",	13, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Ardèche",	1, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Ardennes",	6, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Ariège",	11, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Aube",	6, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Aude",	11, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Aveyron",	11, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Bouches-du-Rhône",	13, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Calvados",	9, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Cantal",	1, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Charente",	10, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Charente-Maritime",	10, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Cher",	4, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Corrèze",	10, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Corse-du-Sud",	5, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Haute-Corse",	5, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Côte-d'Or",	2, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Côtes d'Armor",	3, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Creuse",	10, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Dordogne",	10, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Doubs",	2, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Drôme",	1, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Eure",	9, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Eure-et-Loir",	4, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Finistère",	3, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Gard",	11, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Haute-Garonne",	11, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Gers",	11, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Gironde",	10, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Hérault",	11, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Ille-et-Vilaine",	3, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Indre",	4, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Indre-et-Loire",	4, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Isère",	1, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Jura",	2, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Landes",	10, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Loir-et-Cher",	4, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Loire",	1, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Haute-Loire",	1, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Loire-Atlantique",	12, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Loiret",	4, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Lot",	11, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Lot-et-Garonne",	10, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Lozère",	11, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Maine-et-Loire",	12, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Manche",	9, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Marne",	6, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Haute-Marne",	6, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Mayenne",	12, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Meurthe-et-Moselle",	6, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Meuse",	6, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Morbihan",	3, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Moselle",	6, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Nièvre",	2, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Nord",	7, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Oise",	7, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Orne",	9, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Pas-de-Calais",	7, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Puy-de-Dôme",	1, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Pyrénées-Atlantiques",	10, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Hautes-Pyrénées",	11, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Pyrénées-Orientales",	11, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Bas-Rhin",	6, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Haut-Rhin",	6, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Rhône",	1, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Haute-Saône",	2, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Saône-et-Loire",	2, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Sarthe",	12, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Savoie",	1, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Haute-Savoie",	1, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Paris",	8, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Seine-Maritime",	9, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Seine-et-Marne",	8, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Yvelines",	8, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Deux-Sèvres",	10, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Somme",	7, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Tarn",	11, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Tarn-et-Garonne",	11, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Var",	13, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Vaucluse",	13, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Vendée",	12, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Vienne",	10, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Haute-Vienne",	10, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Vosges",	6, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Yonne",	2, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Territoire de Belfort",	2, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Essonne",	8, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Hauts-de-Seine",	8, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Seine-St-Denis",	8, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Val-de-Marne",	8, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Val-D'Oise",	8, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Guadeloupe",	14, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Martinique",	15, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Guyane",	16, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "La Réunion",	17, NOW(), NOW());
INSERT INTO departements (nomDepartement, refregion, created_at, updated_at) VALUES ( "Mayotte", 18, NOW(), NOW());



INSERT INTO villes(nomville,code_postal,refdepartement, created_at, updated_at) VALUES ('L''Abergement-Clémenciat',1400,1, NOW(), NOW());
INSERT INTO villes(nomville,code_postal,refdepartement, created_at, updated_at) VALUES ('L''Abergement-de-Varey',1640,1, NOW(), NOW());
INSERT INTO villes(nomville,code_postal,refdepartement, created_at, updated_at) VALUES ('Ambérieu-en-Bugey',1500,1, NOW(), NOW());
INSERT INTO villes(nomville,code_postal,refdepartement, created_at, updated_at) VALUES ('Ambérieux-en-Dombes',1330,1, NOW(), NOW());
INSERT INTO villes(nomville,code_postal,refdepartement, created_at, updated_at) VALUES ('Ambléon',1300,1, NOW(), NOW());
INSERT INTO villes(nomville,code_postal,refdepartement, created_at, updated_at) VALUES ('Ambronay',1500,1, NOW(), NOW());
INSERT INTO villes(nomville,code_postal,refdepartement, created_at, updated_at) VALUES ('Ambutrix',1500,1, NOW(), NOW());
INSERT INTO villes(nomville,code_postal,refdepartement, created_at, updated_at) VALUES ('Andert-et-Condon',1300,1, NOW(), NOW());
INSERT INTO villes(nomville,code_postal,refdepartement, created_at, updated_at) VALUES ('Anglefort',1350,1, NOW(), NOW());
INSERT INTO villes(nomville,code_postal,refdepartement, created_at, updated_at) VALUES ('Apremont',1100,1, NOW(), NOW());
INSERT INTO villes(nomville,code_postal,refdepartement, created_at, updated_at) VALUES ('Aranc',1110,1, NOW(), NOW());
INSERT INTO villes(nomville,code_postal,refdepartement, created_at, updated_at) VALUES ('Arandas',1230,1, NOW(), NOW());
INSERT INTO villes(nomville,code_postal,refdepartement, created_at, updated_at) VALUES ('Arbent',1100,1, NOW(), NOW());
INSERT INTO villes(nomville,code_postal,refdepartement, created_at, updated_at) VALUES ('Arboys en Bugey',1300,1, NOW(), NOW());
INSERT INTO villes(nomville,code_postal,refdepartement, created_at, updated_at) VALUES ('Arboys en Bugey',1300,1, NOW(), NOW());
INSERT INTO villes(nomville,code_postal,refdepartement, created_at, updated_at) VALUES ('Arbigny',1190,1, NOW(), NOW());
INSERT INTO villes(nomville,code_postal,refdepartement, created_at, updated_at) VALUES ('Argis',1230,1, NOW(), NOW());
INSERT INTO villes(nomville,code_postal,refdepartement, created_at, updated_at) VALUES ('Armix',1510,1, NOW(), NOW());
INSERT INTO villes(nomville,code_postal,refdepartement, created_at, updated_at) VALUES ('Ars-sur-Formans',1480,1, NOW(), NOW());
INSERT INTO villes(nomville,code_postal,refdepartement, created_at, updated_at) VALUES ('Artemare',1510,1, NOW(), NOW());
INSERT INTO villes(nomville,code_postal,refdepartement, created_at, updated_at) VALUES ('Asnières-sur-Saône',1570,1, NOW(), NOW());
INSERT INTO villes(nomville,code_postal,refdepartement, created_at, updated_at) VALUES ('Attignat',1340,1, NOW(), NOW());
INSERT INTO villes(nomville,code_postal,refdepartement, created_at, updated_at) VALUES ('Bâgé-Dommartin',1380,1, NOW(), NOW());
INSERT INTO villes(nomville,code_postal,refdepartement, created_at, updated_at) VALUES ('Bâgé-le-Châtel',1380,1, NOW(), NOW());
INSERT INTO villes(nomville,code_postal,refdepartement, created_at, updated_at) VALUES ('Balan',1360,1, NOW(), NOW());
INSERT INTO villes(nomville,code_postal,refdepartement, created_at, updated_at) VALUES ('Baneins',1990,1, NOW(), NOW());
INSERT INTO villes(nomville,code_postal,refdepartement, created_at, updated_at) VALUES ('Beaupont',1270,1, NOW(), NOW());


INSERT INTO maisons (refisolation, refstatut, refville, nom, numMaison, rue, created_at, updated_at) VALUES (1, 2, 5,'Maison de Thomas', 64, 'rue robert villoing', NOW(), NOW());
INSERT INTO maisons (refisolation, refstatut, refville, nom, numMaison, rue, created_at, updated_at) VALUES (1, 1, 3,'Maison de Bakari', 52, 'rue paradis', NOW(), NOW());
INSERT INTO maisons (refisolation, refstatut, refville, nom, numMaison, rue, created_at, updated_at) VALUES (1, 3, 9,'Maison de Celine', 13, 'rue guy', NOW(), NOW());

INSERT INTO appartements (reftype, refMaison, refSecurite, nbhabitants, created_at, updated_at) VALUES (1, 2, 1, 5, NOW(), NOW());
INSERT INTO appartements (reftype, refMaison, refSecurite, nbhabitants, created_at, updated_at) VALUES (3, 1, 2, 2, NOW(), NOW());
INSERT INTO appartements (reftype, refMaison, refSecurite, nbhabitants, created_at, updated_at) VALUES (2, 3, 3, 3, NOW(), NOW());

INSERT INTO pieces (libelle, refappartement, reftype, created_at, updated_at) VALUES ('cuisine1', 1, 1, NOW(), NOW());
INSERT INTO pieces (libelle, refappartement, reftype, created_at, updated_at) VALUES ('cuisine2', 1, 1, NOW(), NOW());
INSERT INTO pieces (libelle, refappartement, reftype, created_at, updated_at) VALUES ('Chambre1', 1, 1, NOW(), NOW());
INSERT INTO pieces (libelle, refappartement, reftype, created_at, updated_at) VALUES ('salle de bain1', 1, 3, NOW(), NOW());
INSERT INTO pieces (libelle, refappartement, reftype, created_at, updated_at) VALUES ('cuisine1', 1, 1, NOW(), NOW());
